#!/bin/bash

set -e

clear

RET_DIR=$PWD
CUR_DIR=$(dirname "$0")
cd "$CUR_DIR"
CUR_DIR=$PWD
cd "$RET_DIR"

bash "$CUR_DIR"/00_prepare_install.sh
bash "$CUR_DIR"/01_create_install.sh
bash "$CUR_DIR"/02_install.sh
bash "$CUR_DIR"/99_clear.sh

clear
echo -e "\033[1;36mInstall finished: Ok.\033[0m"
exit 0
